// Reading a tutorial written outside the app.
//
// `readTutorialJson` is the whole of what the import decides, which is why it
// is a function and not a screen: the dialog that shows the report and the
// batch that saves twelve files both ask this one question. The rule the
// batches in this repository keep proving is that a feature with a pure core
// should land that core first — everything the screen could then get wrong is
// drawing.
//
// The files this exists for were generated by an LLM from
// `PGN-TUTORIAL-FORMAT.md`, and twelve of the first twenty-seven had a fault in
// them. That is the normal case rather than the exception, and the cases below
// are the faults that were actually in those files.

import 'package:flutter_test/flutter_test.dart';

import 'package:chess_app/features/lessons/models/lesson_labels.dart';
import 'package:chess_app/features/tutorial_studio/models/tutorial_draft.dart';
import 'package:chess_app/features/tutorial_studio/services/tutorial_import.dart';

/// A rook endgame both sides can be written from: `Ra8+` is a check and not
/// mate, `Kh7` answers it, and there is no knight on the board, so a knight
/// move is a move that cannot be played.
const fen = '6k1/5pp1/7p/8/8/8/5PPP/R5K1 w - - 0 1';

const start = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';

void main() {
  group('a file that cannot be read', () {
    test('is not JSON', () {
      final read = readTutorialJson('not json at all', fileName: 'x.json');
      expect(read.openable, isFalse);
      expect(read.problems.single.fault, ImportFault.refused);
      expect(read.problems.single.sentence, contains('not valid JSON'));
    });

    test('is JSON that is not a tutorial', () {
      final read = readTutorialJson('[1, 2, 3]');
      expect(read.openable, isFalse);
      expect(
          read.problems.single.sentence, contains('does not hold a tutorial'));
    });

    test('has no parts', () {
      final read = readTutorialJson('{"title": "Empty", "positionList": []}');
      expect(read.openable, isFalse);
      expect(read.problems.single.sentence, contains('positionList'));
    });
  });

  group('a clean file', () {
    final read = readTutorialJson('''
{
  "title": "The opposition",
  "description": "Six positions about the opposition",
  "tags": ["endgame", "opposition"],
  "positionList": [
    {
      "title": "Deo 1",
      "fen": "$start",
      "kind": "show",
      "pgn": "{ Watch the centre. [%csl Ge4] }\\n1. e4 { A sentence. }\\n*"
    },
    {
      "title": "Deo 2",
      "fen": "$fen",
      "kind": "ask_move",
      "instruction": "Find the best move.",
      "solutionSan": "Ra8+"
    }
  ]
}
''', fileName: 'opposition.json');

    test('has nothing wrong with it', () {
      expect(read.problems, isEmpty);
      expect(read.clean, isTrue);
      expect(read.storable, isTrue);
    });

    test('reads the title, the description and the labels', () {
      expect(read.title, 'The opposition');
      expect(read.description, 'Six positions about the opposition');
      expect(read.tags, ['endgame', 'opposition']);
    });

    test('keeps the parts in order, with their own fields', () {
      expect(read.partCount, 2);
      expect(read.positionList[0]['title'], 'Deo 1');
      expect(read.positionList[1]['kind'], 'ask_move');
      expect(read.positionList[1]['solutionSan'], 'Ra8+');
      expect(read.positionList[1]['instruction'], 'Find the best move.');
    });

    test('opens as a draft that has never been saved', () {
      // The whole point of the entry: the studio's first "Save tutorial" has to
      // create a tutorial, not edit one. A `lessonId` read out of a file would
      // write over somebody's existing tutorial — or answer 404.
      final draft = TutorialDraft.fromLesson(read.asLesson);
      expect(draft.lessonId, isNull);
      expect(draft.title, 'The opposition');
      expect(draft.tags, ['endgame', 'opposition']);
      expect(draft.description, 'Six positions about the opposition');
      expect(draft.sections.length, 2);
      // Read through the child's own parser, so the line is there rather than
      // the text of it.
      expect(draft.sections.first.root.children, isNotEmpty);
    });
  });

  group('the id in a file', () {
    test('is dropped, so the server mints a fresh one', () {
      // A step id resolves a schedule row and a recorded answer. The same file
      // imported twice would name the same ids twice, and a child's progress
      // would show up in the wrong copy — with nothing to complain, because
      // nothing joins on a step id.
      final read = readTutorialJson('''
{
  "title": "With ids",
  "positionList": [
    {"id": "a3f9c1d2", "fen": "$fen", "kind": "show"}
  ]
}
''');
      expect(read.positionList.single.containsKey('id'), isFalse);
      expect(read.problems, isEmpty);
    });
  });

  group('a part the server would refuse', () {
    test('an unreadable position', () {
      // `2c2n2` — a piece called c, which is what one generated file actually
      // contained.
      final read = readTutorialJson('''
{
  "title": "Bad FEN",
  "positionList": [
    {"fen": "2r1r1k1/p2q1ppp/2c2n2/3p4/N2P4/P3PN2/2Q2PPP/2R2RK1 w - - 0 1"}
  ]
}
''');
      expect(read.storable, isFalse);
      expect(read.problems.single.fault, ImportFault.refused);
      expect(read.problems.single.sentence, startsWith('Part 1:'));
    });

    test('and nothing else is asked about that part', () {
      // Everything below the FEN check needs a position to ask in. Two
      // sentences about one part, the second of them nonsense, is how a report
      // stops being read.
      final read = readTutorialJson('''
{
  "title": "Bad FEN",
  "positionList": [
    {"fen": "nonsense", "kind": "ask_move", "pgn": "1. e4 *"}
  ]
}
''');
      expect(read.problems.length, 1);
    });

    test('a move question with no solution', () {
      final read = readTutorialJson('''
{
  "title": "No solution",
  "positionList": [
    {"fen": "$fen", "kind": "ask_move", "instruction": "Find it."}
  ]
}
''');
      expect(read.storable, isFalse);
      expect(read.problems.single.sentence, contains('gives no solution'));
    });

    test('a solution that cannot be played in its own position', () {
      final read = readTutorialJson('''
{
  "title": "Illegal solution",
  "positionList": [
    {"fen": "$fen", "kind": "ask_move", "solutionSan": "Qe5+"}
  ]
}
''');
      expect(read.storable, isFalse);
      expect(read.problems.single.sentence, contains('"Qe5+"'));
    });

    test('a choice question with one answer, and one with no correct answer',
        () {
      final one = readTutorialJson('''
{
  "title": "One answer",
  "positionList": [
    {"fen": "$fen", "kind": "ask_choice", "choices": [{"text": "a", "correct": true}]}
  ]
}
''');
      expect(one.problems.single.sentence, contains('two and four'));

      final none = readTutorialJson('''
{
  "title": "No correct answer",
  "positionList": [
    {"fen": "$fen", "kind": "ask_choice",
     "choices": [{"text": "a", "correct": false}, {"text": "b"}]}
  ]
}
''');
      expect(none.problems.single.sentence, contains('correct one'));
    });

    test('a kind nobody has heard of', () {
      final read = readTutorialJson('''
{
  "title": "Odd kind",
  "positionList": [{"fen": "$fen", "kind": "ask_everything"}]
}
''');
      expect(read.storable, isFalse);
      expect(read.problems.single.sentence, contains('ask_everything'));
    });
  });

  group('a part that would be stored and would be wrong', () {
    test('a line that does not replay from its own position', () {
      // The silent one: the server has no PGN reader, so this is stored without
      // complaint and the child simply gets a shorter lesson than the file
      // holds. `LessonStepLine` counts the moves it could not play.
      final read = readTutorialJson('''
{
  "title": "Wrong line",
  "positionList": [
    {"fen": "$fen", "kind": "show", "pgn": "1. Nf3 { A sentence. } Nf6\\n*"}
  ]
}
''');
      expect(read.storable, isTrue, reason: 'the server would take it');
      expect(read.clean, isFalse, reason: 'and it would be wrong');
      expect(read.problems.single.fault, ImportFault.damaged);
      expect(read.problems.single.sentence, contains('2 moves'));
    });

    test('one rejected move is counted in the singular', () {
      final read = readTutorialJson('''
{
  "title": "Glyph",
  "positionList": [
    {"fen": "$fen", "kind": "show", "pgn": "1. Ra8+ { Check. } Kh7 2. Kg2+- \\n*"}
  ]
}
''');
      expect(read.problems.single.sentence, contains('1 move that cannot'));
    });

    test('a move question carrying the line that answers it', () {
      final read = readTutorialJson('''
{
  "title": "Leaky",
  "positionList": [
    {"fen": "$fen", "kind": "ask_move", "solutionSan": "Ra8+",
     "pgn": "1. Ra8+ { The only move. } Kh7\\n*"}
  ]
}
''');
      expect(read.problems.single.fault, ImportFault.damaged);
      expect(read.problems.single.sentence, contains('shown the answer'));
    });

    test('a demonstration with a line is not a leak', () {
      // The negative half. A `show` part is a line, and a report that calls
      // every line a leak is a report nobody reads.
      final read = readTutorialJson('''
{
  "title": "Fine",
  "positionList": [
    {"fen": "$fen", "kind": "show", "pgn": "1. Ra8+ { Check. } Kh7\\n*"}
  ]
}
''');
      expect(read.problems, isEmpty);
    });
  });

  group('the title', () {
    test('comes from the file name when the file gives none', () {
      final read = readTutorialJson(
        '{"positionList": [{"fen": "$fen"}]}',
        fileName: 'D:/chess/01_direktna_opozicija.json',
      );
      expect(read.title, '01 direktna opozicija');
    });

    test('is shortened rather than left to overflow the column', () {
      final long = 'a' * 400;
      final read = readTutorialJson(
        '{"title": "$long", "positionList": [{"fen": "$fen"}]}',
      );
      expect(read.title.length, maxImportedTitle);
    });
  });

  group('the labels', () {
    test('are read from tags, labels or a single label', () {
      for (final field in ['tags', 'labels']) {
        final read = readTutorialJson(
          '{"title": "T", "$field": ["endgame"], "positionList": [{"fen": "$fen"}]}',
        );
        expect(read.tags, ['endgame'], reason: field);
      }
      final one = readTutorialJson(
        '{"title": "T", "label": "endgame", "positionList": [{"fen": "$fen"}]}',
      );
      expect(one.tags, ['endgame']);
    });

    test('are trimmed and deduplicated on the way in', () {
      final read = readTutorialJson(
        '{"title": "T", "tags": [" endgame ", "Endgame", "", "rook"], '
        '"positionList": [{"fen": "$fen"}]}',
      );
      expect(read.tags, ['endgame', 'rook']);
    });

    test('a whole batch can be labelled at once, keeping its own', () {
      final read = readTutorialJson(
        '{"title": "T", "tags": ["endgame"], "positionList": [{"fen": "$fen"}]}',
      );
      final labelled = read.withLabels(['gemini', 'endgame']);
      expect(labelled.tags, ['endgame', 'gemini']);
      // And nothing else about the tutorial moved.
      expect(labelled.title, read.title);
      expect(labelled.partCount, read.partCount);
      expect(labelled.problems.length, read.problems.length);
    });
  });

  group('normaliseLabels', () {
    test('drops the empty, keeps the first spelling, caps the length', () {
      expect(normaliseLabels(['  ', 'Rook', 'rook', 'ROOK']), ['Rook']);
      expect(normaliseLabels(['a' * 300]).single.length, maxLabelLength);
    });

    test('stops at the limit rather than refusing', () {
      final many = [for (var i = 0; i < 40; i++) 'label$i'];
      expect(normaliseLabels(many).length, maxLabelsPerLesson);
    });
  });
}
